# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
r_build_args: "--compact-vignettes"
r_packages:
  - devtools
r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown
os:
  - linux
r:
  - release
  - devel
env:
  - COMPILER=gxx
matrix:
  fast_finish: true
  include:
    - os: osx
      r: release
      env: COMPILER=clang
    - os: linux
      r: release
      env: COMPILER=gxx
      env: RLANG=devel
      r_github_packages:
        - r-lib/rlang
  allow_failures:
    - r: devel
    - r: release
      env: RLANG=devel
before_install:
  - |
    Rscript() {
      # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
      # https://unix.stackexchange.com/a/109790/219144
      while sleep 60; do echo "=====[ still running ]====="; tail -n 10 /tmp/rs.out; done &
      command Rscript "$@" > /tmp/rs.out 2>&1
      local status=$?
      kill %1
      tail -n 50 /tmp/rs.out
      return $status
    }
deploy:
  provider: script
  script: Rscript -e 'if (grepl("linux", Sys.info()[["sysname"]], ignore.case = TRUE)) pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"
after_success:
  - if [[ ("$TRAVIS_R_VERSION_STRING" == "release") && ("$TRAVIS_OS_NAME" == "linux") ]]; then
      Rscript codecov.R;
    fi
notifications:
  email:
    on_success: change
    on_failure: change
