# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
r_build_args: "--compact-vignettes"
r_packages:
  - devtools
env:
  - DEPS=release
matrix:
  fast_finish: true
  include:
    - os: linux
      r: release
      r_packages:
        - devtools
        - covr
        - pkgdown
      after_success:
        Rscript codecov.R
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        on:
          branch: docs
    - os: osx
      r: release
    - os: linux
      r: devel
    - os: linux
      r: release
      env: DEPS=devel
      r_github_packages:
        - r-lib/rlang
        - Rdatatable/data.table
  allow_failures:
    - os: linux
      r: devel
    - os: linux
      r: release
      env: DEPS=devel
before_install:
  - |
    Rscript() {
      # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
      # https://unix.stackexchange.com/a/109790/219144
      while sleep 60; do echo "=====[ still running ]====="; tail -n 10 /tmp/rs.out; done &
      command Rscript "$@" > /tmp/rs.out 2>&1
      local status=$?
      kill %1
      tail -n 50 /tmp/rs.out
      return $status
    }
notifications:
  email:
    on_success: change
    on_failure: change
