# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
r_build_args: "--compact-vignettes"
r_packages:
  - devtools
os:
  - linux
r:
  - devel
env:
  - RLANG=release
matrix:
  fast_finish: true
  include:
    - os: linux
      r: release
      r_github_packages:
        - r-lib/covr
        - r-lib/pkgdown
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        on:
          branch: master
    - os: osx
      r: release
    - os: linux
      r: release
      env: RLANG=devel
      r_github_packages:
        - r-lib/rlang
  allow_failures:
    - r: devel
    - r: release
      env: RLANG=devel
before_install:
  - |
    Rscript() {
      # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
      # https://unix.stackexchange.com/a/109790/219144
      while sleep 60; do echo "=====[ still running ]====="; tail -n 10 /tmp/rs.out; done &
      command Rscript "$@" > /tmp/rs.out 2>&1
      local status=$?
      kill %1
      tail -n 50 /tmp/rs.out
      return $status
    }
after_success:
  - if [[ ("$TRAVIS_R_VERSION_STRING" == "release") && ("$TRAVIS_OS_NAME" == "linux") ]]; then
      Rscript codecov.R;
    fi
notifications:
  email:
    on_success: change
    on_failure: change
