# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches-ignore:
      - master
      - docs
  pull_request:
    branches:
      - master

name: R-CMD-check non-master

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        continue-on-error: ${{ matrix.config.r == 'devel' }}
        env:
          # https://raw.githubusercontent.com/kalibera/cran-checks/master/rcnst/README.txt
          R_COMPILE_PKGS: 1
          R_JIT_STRATEGY: 4
          R_CHECK_CONSTANTS: 5

      - name: Test coverage
        if: runner.os == 'Linux' && matrix.config.r == 'release'
        run: |
          Rscript -e 'install.packages("covr")'
          Rscript codecov.R
        continue-on-error: true
